version: "3.9"

services:
  api:
    container_name: 4i-api
    build: .
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db

  db:
    container_name: postgres
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Postgres2021!